### ISSUE TITLE
VLT vlt-peer-lag support in ansible-role-dellos-interface

### ISSUE THREAD

**Issue by mzi77** [Dell-Networking/ansible-role-dellos-lag#1]
Could you please add VLT support to this role ?
Martin

**Comment by skg-net** [comment]
Martin,

Thanks for your interest, VLT support is targeted for end of December. We
will keep you posted.

Thanks,
Senthil Kumar G.

**Comment by skg-net** [comment]
@mzi77 we have a new role for vlt. Please refer

https://galaxy.ansible.com/Dell-Networking/dellos-vlt/

**Comment by mzi77** [comment]
Great, I will test it and I will let you know.
